site_name: TrollScript
site_url: https://trollscript.qzz.io
site_description: TrollScript 官方文档与 API 参考
repo_url: https://github.com/dompling/TrollScript-Release

theme:
  name: material
  language: zh
  palette:
    # 自动切换深色/浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式     
  features:
    - navigation.instant      # 页面即时加载 (SPA 体验)
    - navigation.tracking     # 锚点跟随
    - content.code.copy       # 代码块一键复制
    - search.suggest          # 搜索建议
    - search.highlight        # 搜索关键词高亮
    - navigation.sections      # 使左侧菜单以“分组”形式显示，层级感更强
    - navigation.expand        # 默认展开所有左侧菜单项
    - toc.integrate            # 将页面目录(TOC)整合到左侧导航栏

nav:
  - 介绍: README.md             # 对应 docs/index.md
  - 安装指南: INSTALL.md    # 二级菜单示例
  - 环境要求: requirements.md
  - 测试示例脚本: TestScripts.md
  - 功能介绍: ARGS.md
  - API 参考:
    - App: App.md
    - 日历: Calendar.md
    - 剪切板: Clipboard.md
    - Console: Console.md
    - 联系人: Contacts.md
    - 设备: Device.md
    - 显示: Display.md
    - 文件: File.md
    - 网络: HTTP.md
    - HUD: HUD.md
    - 触觉反馈: Haptic.md
    - 定位: Location.md
    - 网络信息: Network.md
    - 通知: Notification.md
    - 提醒: Reminder.md
    - 短信: SMS.md
    - SQL: SQL.md
    - 快捷指令: Shortcuts.md
    - 本地存储: Storage.md
    - 系统: System.md
    - Util: Util.md
    - iCloud: iCloud.md
  - 常见问题: FAQ.md


markdown_extensions:
  - toc:
      permalink: true
  - admonition                # 警告/提示框
  - pymdownx.details          # 折叠详情
  - pymdownx.superfences      # 嵌套代码块
  - pymdownx.tabbed:          # 选项卡
      alternate_style: true